### ISSUE TITLE
main() 에서는 scoreService.inputScore() 를 한번만 호출 해야 합니다

### ISSUE THREAD

**Issue by callor** [loo919239/Biz-2023-11-505-Java#2]
![image](https://github.com/loo919239/Biz-2023-11-505-Java/assets/23270330/9638918f-3be5-4d08-a01a-6f30a91b18c9)

main() 에서는 inputScore() 를 한번만 호출하고
inputScore() 에서 10명 학생의 데이터를 생성해야 합니다

**Comment by loo919239** [comment]
inputScore() 안에 10명의 학생 데이터를 생성하도록 수정했습니다.
